-- Rates-audit corrections generated by parity/audit/rates_audit.py
-- Sets each value at its true source so engine-effective == workbook exactly.
-- Apply ONLY as a harness-gated fix batch; re-run the full parity suite after.
BEGIN;
COMMIT;
